name: Build Mod
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Geode CLI
        uses: geode-sdk/setup-geode@v1
        with:
          geode-version: "5.10.1"

      - name: Build mod
        run: geode build

      - name: Upload compiled mod
        uses: actions/upload-artifact@v4
        with:
          name: mod
          path: build/*.geode
