name: Build Mod
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/geode-sdk/cli:5.10.1
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build mod
        run: geode build

      - name: Upload compiled mod
        uses: actions/upload-artifact@v4
        with:
          name: mod
          path: build/*.geode
