name: Build Mod
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [win]
    steps:
      - uses: actions/checkout@v4
      - name: Build Geode Mod
        uses: geode-sdk/build-geode-mod@v1
        with:
          geode-version: "5.10.1"
          target: ${{ matrix.target }}
